//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DipSA45Team12a
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCatalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookCatalogue()
        {
            this.BookInfoes = new HashSet<BookInfo>();
        }
    
        public double ISBN { get; set; }
        public string BookTitle { get; set; }
        public int StockInLibrary { get; set; }
        public int NumberOnLoan { get; set; }
        public string Author { get; set; }
        public System.DateTime YearOfPublication { get; set; }
        public string Publisher { get; set; }
        public string Description { get; set; }
        public string Subject { get; set; }
        public string Type { get; set; }
        public string CallNumber { get; set; }
        public string ShelfNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookInfo> BookInfoes { get; set; }
    }
}
