//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DipSA45Team12a
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransDetail
    {
        public int Sn { get; set; }
        public int TransID { get; set; }
        public double BookID { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
        public virtual LoanTran LoanTran { get; set; }
    }
}
